version: '3.7'

services:
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: TaskDB
      POSTGRES_USER: user-test
      POSTGRES_PASSWORD: teste123
    ports:
      - 5432:5432

  tasklist-app:
    build: .
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - postgres
    entrypoint: ["sh", "-c", "dotnet ef database update --project TaskList.Data/TaskList.Data.csproj --startup-project TaskList/TaskList.API.csproj && dotnet TaskList.API.dll"]

volumes:
  postgres_data:
    driver: local